// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
}

type Document struct {
	ID string `json:"id"`
}

func (Document) IsEntity() {}
func (Document) IsNode()   {}

type Todo struct {
	ID string `json:"id"`
}

func (Todo) IsEntity() {}
func (Todo) IsNode()   {}
